### ISSUE TITLE
Dokumentation schreiben

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/geobrains_demo#24]
In der Datei readme.md sollten wir so langsam anfangen zu dokumentieren. Folgende Punkte sind dabei vor allem wichtig:

- Welche Daten kommen in welches Feld?
- Welcher Datentyp?
- Wie heißt das zugehörige Feld in der Datenbank, wo der Wert gespeichert wird?
- Welche Restriktionen gibt es?
- Link zur Dokumentation von DataCite mit der Beschreibung des Elements im Metadaten-Schema?

Was ist sonst noch wichtig?

**Comment by Ali-GeoFZ** [comment]
-Versionierung

-Beispielwerte für jedes Feld

-Datenvalidierung:
Feststellen, welche Felder zwingend ausgefüllt werden müssen und welche optional leer bleiben können
